apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
      - name: mycontainer
        image: ramirk/llm_demo
        ports:
        - containerPort: 7860

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc-v2
spec:
  type: NodePort
  selector:
    app: myapp-pod
  ports:
  - port: 5000 # Service IP Port
    targetPort: 7860 # Container Port
    nodePort: 30002 # Node Port/Host Port
    protocol: TCP