apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    environment: prod
spec:
  containers:
  - name: myapp
    image: ramirk/demo_rag
    ports:
      - containerPort: 7860

